

services:
  postgres_DB:
    image: postgres
    container_name: postgres_DB
    restart: always
    environment:
      POSTGRES_USER: tommy
      POSTGRES_PASSWORD: 900128
      postgres_DB: distance_method
    ports:
      - "5432:5432"
    volumes:
      - /Users/chenyanjia/DB/postgre:/var/lib/postgresql/data

  Web:
    build: ./distance_method
    container_name: Distance
    image: distance:v1
    restart: always
  
    ports:
      - "1985:1985"
    depends_on:
      - postgres_DB
    environment:
      DATABASE_HOST: postgres_DB
      DATABASE_PORT: 5432
      DATABASE_NAME: distance_method
      DATABASE_USER: tommy
      DATABASE_PASSWORD: 900128
    #將資料從本機掛載
    volumes:
      - /Users/chenyanjia/MyDjango/mydjango/finance/distance_method/common/tracker_results:/app/tracker_results
  accounts:
    build: ./accounts
    image: accounts:1
    container_name: accounts
    restart: always
  
    ports:
      - "1984:1984"
    depends_on:
      - postgres_DB
    environment:
      DATABASE_HOST: postgres_DB
      DATABASE_PORT: 5432
      DATABASE_NAME: distance_method
      DATABASE_USER: tommy
      DATABASE_PASSWORD: 900128
      AUTH_PATH: http://0.0.0.0:1984/account/
      WEB_PATH: http://0.0.0.0:1985/correlation/
      PYTHONUNBUFFERED: 1
    volumes:
      - ./accounts:/app
  FuncAPI:
    build: ./function_api
    image: func_api:v1
    container_name: FuncAPI
    restart: always
    ports: 
      - 1986:1986
    environment:
      PYTHONUNBUFFERED: 1
volumes:
  postgres_data:
