# Generated by Django 5.1.2 on 2025-01-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock1', models.CharField(max_length=10)),
                ('stock2', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('window_size', models.IntegerField()),
                ('n_times', models.IntegerField()),
                ('date', models.DateField()),
                ('stock1_close', models.FloatField()),
                ('stock2_close', models.FloatField()),
                ('spread', models.FloatField()),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('final_value', models.FloatField(blank=True, null=True)),
                ('profit_percent', models.FloatField(blank=True, null=True)),
                ('daily_value', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
